# Generated by Django 4.1.3 on 2022-12-02 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rev', '0004_alter_film_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='director',
        ),
        migrations.AddField(
            model_name='film',
            name='directors',
            field=models.ManyToManyField(to='rev.director'),
        ),
    ]
